App\Entity\Choice:
    attributes:
        id:
            groups:
                - question:read
                - workflow:read
        text:
            groups:
                - question:read
                - question:write
                - workflow:read
