App\Entity\Pass:
    attributes:
        id:
            groups:
                - workflow:read
        name:
            groups:
                - workflow:read

App\Model\Pass:
    attributes:
        id:
            groups:
                - pass:collection:read
        name:
            groups:
                - pass:collection:read
        description:
            groups:
                - pass:collection:read
        prices:
            groups:
                - pass:collection:read

App\Model\Price:
    attributes:
        id:
            groups:
                - pass:collection:read
        amount:
            groups:
                - pass:collection:read
