services:
  php:
    volumes:
      - ./api:/app
    ports:
      - "8000:80"

  front:
    volumes:
      - type: bind
        source: ./front
        target: /app
      - type: volume
        source: front_node_modules
        target: /app/node_modules
        volume:
          nocopy: true
    ports:
      - "3000:3000"

  storybook:
    command: sh -c "pnpm install --frozen-lockfile --ignore-scripts=false && pnpm storybook --host 0.0.0.0 --no-open --disable-telemetry"
    volumes:
      - type: bind
        source: ./front
        target: /app
      - type: volume
        source: front_node_modules
        target: /app/node_modules
        volume:
          nocopy: true
    ports:
      - "6006:6006"

  db:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comutitres
    volumes:
      - db_data:/var/lib/mysql

  mailbox:
    ports:
      - "8025:8025"

volumes:
  front_node_modules:
