services:
  php:
    depends_on:
      - db
    build:
      context: ./api
      target: ${DOCKER_TARGET:-dev}
    working_dir: /app

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    depends_on:
      - db

  db:
    image: mariadb:12.3

  front:
    build:
      context: ./front
      target: ${DOCKER_TARGET:-dev}

  mailbox:
    image: mailhog/mailhog

volumes:
  db_data:
