# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    front_url: '%env(resolve:FRONT_URL)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $frontUrl: '%front_url%'

    App\:
        resource: '../src/'

    App\Service\DocumentManager:
        bind:
            $directory: '%kernel.project_dir%/documents'

    gedmo.mapping.driver.attribute:
        class: Gedmo\Mapping\Driver\AttributeReader

    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_listener, event: 'postLoad' }
            - { name: doctrine.event_listener, event: 'postPersist' }
            - { name: doctrine.event_listener, event: 'preFlush' }
            - { name: doctrine.event_listener, event: 'onFlush' }
            - { name: doctrine.event_listener, event: 'loadClassMetadata' }
        calls:
            - [ setAnnotationReader, [ '@gedmo.mapping.driver.attribute' ] ]
            # The Kernel's `locale` parameter is used to configure the default locale for the extension
            - [ setDefaultLocale, [ '%kernel.default_locale%' ] ]
            - [ setTranslationFallback, [ '%stof_doctrine_extensions.translation_fallback%' ] ]

    Gedmo\Translatable\TranslatableListener:
        alias: gedmo.listener.translatable
